---      #make sure the local host is in the host file from start maby promt and put input of promt in hostfile or ip a and get address or read form file with ip addresses
  - name: get rights
    hosts: 10.0.1.26
    become: true
    become_method: sudo
    vars:
      ansible_become_password: sb
      github_user: craftstino
      github_token: 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 #nog in de ansible vault steken 

    tasks:
      - name: install prometheus
        apt:
          name: 
          - prometheus
          - nmap
          - rpm
          state: present

      - name: Install nmap RPM package
        shell: sudo rpm -vhU --nodeps https://nmap.org/dist/nmap-7.92-1.x86_64.rpm
        ignore_errors: yes

      - name: git clone
        git:
          repo: https://{{ github_user }}:{{ github_token }}@github.com/BMV429/automated_network_manager
          dest: /home/sb/repo
          clone: yes
          update: yes   

      - name: Copy folder and its files
        copy:
          src: /home/sb/repo/prometheus.yml
          dest: /etc/prometheus/prometheus.yml
             
      - name: Copy folder and its files
        copy:
          src: /home/sb/repo/network_scan
          dest: /home/sb

      - name: Set file mode to 777
        file:
          path: /home/sb/network_scan/get_snmp_host.sh
          mode: "777"

      - name: Set file mode to 777
        file:
          path: /home/sb/network_scan/get_snmp_host.py
          mode: "777"

      - name: Change ownership of directory
        file:
          path: /home/sb/network_scan
          owner: sb
          group: sb

      - name: remove file                     # kan later weg 
        file:
         path: /home/sb/network_scan/nmap.xml
         state: absent   
  
      - name: Run script get_snmp_host.sh
        script: /home/sb/network_scan/get_snmp_host.sh

      - name: remove file                      #kan later weg 
        file:
         path: /home/sb/network_scan/hosts.txt
         state: absent


      - name: Copy folder and its files #waarom deze file hier word uitgelezen en niet in de map van   
        copy:
          src: /home/sb/network_scan/nmap.xml
          dest: /home/sb/

      - name: run python script
        command: python3 /home/sb/network_scan/get_snmp_host.py   

      - name: Read source file contents
        slurp:
          src: /home/sb/hosts.txt
        register: source_contents

      - name: Append source file contents to destination file
        lineinfile:
          dest: /etc/ansible/hosts
          insertafter: EOF
          line: "{{ source_contents.content | b64decode }}"

      - name: Copy folder and its files 
        copy:
          src: /home/sb/target.json
          dest: /etc/prometheus/       

      - name: Copy folder and its files 
        copy:
          src: /home/sb/targetlinux.json
          dest: /etc/prometheus/     

      - name: Copy folder and its files 
        copy:
          src: /home/sb/targetwindows.json
          dest: /etc/prometheus/     

      - name: Copy folder and its files 
        copy:
          src: /home/sb/targetpfsense.json
          dest: /etc/prometheus/     

      - name: Copy folder and its files 
        copy:
          src: /home/sb/targetcisco.json
          dest: /etc/prometheus/     

      - name: Stop service
        systemd:
          name: prometheus
          state: stopped   

      - name: Start service
        systemd:
          name: prometheus
          state: started
     
      - name: git download
        get_url:
          url: https://github.com/prometheus/snmp_exporter/releases/download/v0.21.0/snmp_exporter-0.21.0.linux-amd64.tar.gz
          dest: /home/sb/repo

      - name: Extract tar archive
        unarchive:
          src: /home/sb/repo/snmp_exporter-0.21.0.linux-amd64.tar.gz
          dest: /home/sb/repo/

      - name: Copy folder and its files 
        copy:
          src: /home/sb/repo/snmp.yml
          dest: /home/sb/repo/snmp_exporter-0.21.0.linux-amd64/snmp.yml   

      - name: Copy 
        copy:
          src: /home/sb/repo/snmp.yml
          dest: /home/sb/snmp.yml

      - name: Run script get_snmp_host.sh
        shell: /home/sb/repo/snmp_exporter-0.21.0.linux-amd64/snmp_exporter &  

      - name: Copy file to target system    #kan later weg gewoon vervangen door prometheus.yml in github aan te passen met test.yml 
        copy:
          src: /home/sb/repo/test.yml
          dest: /etc/prometheus/prometheus.yml

      - name: Stop service
        systemd:
          name: prometheus
          state: stopped   

      - name: Start service
        systemd:
          name: prometheus
          state: started        
