---

# Playbook that deploys the rsyslog configuration.

- name: Deploy syslog client config (Windows)
  hosts: windows
  remote_user: sb
  become: true
  become_method: sudo
  gather_facts: false
  vars:
    rsyslog_server_ip: '10.0.1.30'
  tasks:
    # TODO:
    # https://docs.ansible.com/ansible/latest/os_guide/windows_usage.html
    # https://www.loggly.com/ultimate-guide/centralizing-windows-logs/