---
- name: Enable syslog logging on Cisco router
  hosts: localhost
  gather_facts: no #yes

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
     
    - name: Enable logging
      ios_config:
        lines:
          - "logging host {{ ansible_server_ip }}"
          - "logging source-interface Loopback 0"
          - "logging trap debugging" # Change to notification or whatever later.
      delegate_to: "{{ item }}"
      with_items: "{{ groups['IOS'] }}"
      run_once: true
