---


    - name: Update repositories and make sure dependences are installed.
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - apt-transport-https
        - software-properties-common
        - wget
        
    - name: Import keyrings.
      shell: sudo wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key
      
    - name: Add 'stable releases' repository.
      shell: echo "deb [ signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
      
    - name: Update repositories.
      shell: sudo apt-get update
      
    - name: Install Grafana.
      apt:
        name: grafana
        update_cache: yes
        
    - name: Start Grafana service.
      service:
        name: grafana-server
        state: started
        
    - name: Start Grafana service on boot.
      service:
        name: grafana-server
        enabled: yes
        
    - name: Send config files (1/3)
      template:
        src: /home/sb/automated_network_manager/templates/grafana_datasources.yml.j2
        dest: /etc/grafana/provisioning/datasources/prometheus.yml
        
    - name: Send config files (2/3)
      template:
        src: /home/sb/automated_network_manager/templates/grafana_dashboards.yml.j2
        dest: /etc/grafana/provisioning/dashboards/main.yml
        
    - name: Send config files (3/3)
      template:
        src: /home/sb/automated_network_manager/templates/cluster.json.j2
        dest: /var/lib/grafana/dashboards/cluster.json
