- name: Change rsyslog server nexus switch
  hosts: localhost
  gather_facts: no 
  
  vars:
    ansible_connection: network_cli
    ansible_network_os: nxos
    ansible_become: yes

  tasks:
    - name: Eneter configuration mode
      nxos_command: 
        commands:
          - conf t
          - "logging server {{ ansible_server_ip }}"
          - "logging source-interface Loopback 0"
      delegate_to: "{{ client_ip }}"      
