- name: Change dns server nexus switch
  hosts: localhost
  gather_facts: no 
  
  vars:
    ansible_connection: network_cli
    ansible_network_os: nxos
    ansible_become: yes

  tasks:

    - name: Get previous ethernet info 
      nxos_command: 
        commands:
          - "show run interface ethernet {{ interface1 }}"
      delegate_to: "{{ client_ip }}"
      register: show_output

    - name: Create a file
      copy:
        dest: /home/anmt_user/ethernetinfotrunk.txt
        content: "{{ show_output.stdout_lines }}"
      delegate_to: localhost

    - name: Get previous vlan info
      nxos_command: 
        commands:
          - conf t
          - interface ethernet {{ interface1 }}
          - switchport mode trunk
          - no switchport access vlan {{vlan_id}}
          - switchport trunk allowed vlan {{ vlan_id }}
          - switchport trunk native vlan 999
      delegate_to: "{{ client_ip }}"
